Repository slackapi/node-slack-sdk, pull requests merged in 2022-08, with the labels that each got.

#1519 Update @slack/client README to reflect deprecation
  packages/client/README.md
Labels: docs

#1522 Always handle web socket open when connecting
  packages/socket-mode/src/SocketModeClient.ts
Labels: bug

#1524 avoid creating unnecessary function
  packages/web-api/src/helpers.ts
Labels: pkg:web-api
